services:
  frontend:
    image: node:22-alpine
    container_name: frontend
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    depends_on:
      - backend

  backend:
    image: node:22-alpine
    container_name: backend
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - 4000:4000
    env_file: ./backend/.env
    environment:
      - DBHOST=db

  db:
    image: postgres:17-alpine
    container_name: db_container
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      ./backend/.env
    environment:
     - POSTGRES_PASSWORD=postgres