services:
  frontend:
    image: node:22-alpine
    container_name: frontend
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - backend
      - db

  backend:
    image: node:22-alpine
    container_name: backend
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - 4000:4000
    env_file: .env
    environment:
      DB_HOST: db
      SERVER_PORT: ${SERVER_PORT}

  db:
    image: postgres:17-alpine
    container_name: db_container
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-APIBank}
